### PR TITLE
Consolidate libgit2 changes

### PR DESCRIPTION
**Pull request by tiennou**
This is an attempt at consolidating changes made to `libgit2`'s clar somewhere, I'm filing it mostly for reference and to have the list handy (I had started a few month ago, but the recent discussion spurred me to finish it). Changes might have been applied in a different order though.

Copying the current clar files from `libgit2` on top of this will result in this diff, so I think I missed a commit somewhere :

```diff
diff --git i/generate.py w/generate.py
index 993fb274e..572a57f86 100755
--- i/generate.py
+++ w/generate.py
@@ -76,7 +76,7 @@ def render(self):
     def __init__(self, name):
         self.name = name
 
-        self.mtime = None
+        self.mtime = 0
         self.enabled = True
         self.modified = False
 
@@ -222,16 +222,18 @@ def write(self):
             return False
 
         with open(output, 'w') as data:
-            for module in self.modules.values():
+            modules = sorted(self.modules.values(), key=lambda module: module.name)
+
+            for module in modules:
                 t = Module.DeclarationTemplate(module)
                 data.write(t.render())
 
-            for module in self.modules.values():
+            for module in modules:
                 t = Module.CallbacksTemplate(module)
                 data.write(t.render())
 
             suites = "static struct clar_suite _clar_suites[] = {" + ','.join(
-                Module.InfoTemplate(module).render() for module in sorted(self.modules.values(), key=lambda module: module.name)
+                Module.InfoTemplate(module).render() for module in modules
             ) + "\n};\n"
 
             data.write(suites)

```

### CODE REVIEW

**Comment by vmg** [comment]
@tiennou: If you could just create a commit with the small diff we're missing, I'll gladly merge this just to keep this version of the library up to date.

**Comment by tiennou** [comment]
Sure, I'm only missing a commit message 😆. It's moving around some sorting… things… to make sure it's consistent something modules something templates ?

**Comment by tiennou** [comment]
So, I've found the change that seemed sort-related in `libgit2`, and discarded the other (`self.mtime`) as a "revert" of 35770304b80944e814af1ee59eda526000702c4c.

**Comment by vmg** [comment]
Thanks for taking the effort to keep the history between repositories. :bow:

**Pull request merged**
